### ISSUE TITLE
MySQL error,

### ISSUE THREAD

**Issue by mightymaxv2** [mattbeedle/usda-nutrient-database#20]
Error received after successful migration file imports on <code>rake db:migrate</code> in a clean (new) rails application. All remove_index functions are getting some sort of error, be it this, or other. 

<code>
== 20160609043411 AddReferentialIntegrity: migrating ==========================
-- remove_index(:usda_nutrients, :nutrient_number)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
Mysql2::Error:' Error on rename of './fooder/#sql-400_23' to './fooder/usda_nutrients' (errno: 150 - Foreign key constraint is incorrectly formed): DROP INDEX 'index_usda_nutrients_on_nutrient_number' ON 'usda_nutrients'
/home/xxx/Sites/fooder/db/migrate/20160609043411_add_referential_integrity.usda_nutrient_database_engine.rb:4:in 'change'
-e:1:in '<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Error on rename of './fooder/#sql-400_23' to './fooder/usda_nutrients' (errno: 150 - Foreign key constraint is incorrectly formed): DROP INDEX 'index_usda_nutrients_on_nutrient_number' ON 'usda_nutrients'
/home/xxx/Sites/fooder/db/migrate/20160609043411_add_referential_integrity.usda_nutrient_database_engine.rb:4:in 'change'
-e:1:in '<main>'
Mysql2::Error: Error on rename of './fooder/#sql-400_23' to './fooder/usda_nutrients' (errno: 150 - Foreign key constraint is incorrectly formed)
/home/xxx/Sites/fooder/db/migrate/20160609043411_add_referential_integrity.usda_nutrient_database_engine.rb:4:in 'change'
-e:1:in '<main>'
Tasks: TOP => db:migrate
</code>

Error on <code>rake db:migrate</code> after commenting the full referential integrity migration:

<code>
== 20160609043412 FixFootnotesIndexes: migrating ==============================
-- change_table(:usda_footnotes)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
Mysql2::Error: Cannot drop index 'index_usda_footnotes_on_nutrient_databank_number': needed in a foreign key constraint: DROP INex_usda_footnotes_on_nutrient_databank_number' ON 'usda_footnotes'
/home/xxx/Sites/fooder/db/migrate/20160609043412_fix_footnotes_indexes.usda_nutrient_database_engine.rb:5:in 'block in chang
/home/xxx/Sites/fooder/db/migrate/20160609043412_fix_footnotes_indexes.usda_nutrient_database_engine.rb:4:in 'change'
-e:1:in '<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot drop index 'index_usda_footnotes_on_nutrient_databank_number': needed in a key constraint: DROP INDEX 'index_usda_footnotes_on_nutrient_databank_number' ON 'usda_footnotes'
/home/xxx/Sites/fooder/db/migrate/20160609043412_fix_footnotes_indexes.usda_nutrient_database_engine.rb:5:in 'block in chang
/home/xxx/Sites/fooder/db/migrate/20160609043412_fix_footnotes_indexes.usda_nutrient_database_engine.rb:4:in 'change'
-e:1:in '<main>'
Mysql2::Error: Cannot drop index 'index_usda_footnotes_on_nutrient_databank_number': needed in a foreign key constraint
/home/xxx/Sites/fooder/db/migrate/20160609043412_fix_footnotes_indexes.usda_nutrient_database_engine.rb:5:in 'block in chang
/home/xxx/Sites/fooder/db/migrate/20160609043412_fix_footnotes_indexes.usda_nutrient_database_engine.rb:4:in 'change'
-e:1:in '<main>'
Tasks: TOP => db:migrate
</code>

**Comment by mattbeedle** [comment]
hmm, I haven't been testing on MySQL. I'll take a look into this. TBH I'm kind of thinking that moving to compound keys was a mistake. I may move back to v1 style UUID primary keys. For now, you could try using an older version `gem 'usda-nutrient-database', '~> 1.4.0'`

**Comment by mightymaxv2** [comment]
Okay, great. Will do, thanks!

**Comment by mightymaxv2** [comment]
Actually, I'm still getting an error on that class. Although this time, it's not crashing at the beginning of the file. Is there an earlier version? or is there an easy fix? 

<code>
Mysql2::Error: Can't write; duplicate key in table '#sql-400_33': ALTER TABLE `usda_foods` ADD CONSTRAINT `fk_rails_0d82ac9394`
FOREIGN KEY (`food_group_code`)
  REFERENCES `usda_food_groups` (`code`)
/home/xxx/Sites/fooder/db/migrate/20160610185535_add_referential_integrity.usda_nutrient_database_engine.rb:53:in `change'
-e:1:in `<main>'
ActiveRecord::StatementInvalid: Mysql2::Error: Can't write; duplicate key in table '#sql-400_33': ALTER TABLE `usda_foods` ADD CONSTRAINT `fk_rails_0d82ac9394`
FOREIGN KEY (`food_group_code`)
  REFERENCES `usda_food_groups` (`code`)
/home/xxx/Sites/fooder/db/migrate/20160610185535_add_referential_integrity.usda_nutrient_database_engine.rb:53:in `change'
-e:1:in `<main>'
Mysql2::Error: Can't write; duplicate key in table '#sql-400_33'
/home/xxx/Sites/fooder/db/migrate/20160610185535_add_referential_integrity.usda_nutrient_database_engine.rb:53:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
</code>

**Comment by mattbeedle** [comment]
ah, yes, that's because I managed to add the exact same foreign key twice in the same migration :facepalm:, as pointed out by @ignisf [here](https://github.com/mattbeedle/usda-nutrient-database/commit/0bb0eb323d966a42af57c87eb7606bd77f54434c#commitcomment-17307019). You could just manually fix that migration for now. I'll try to find time to back port a fix for that and faster imports into 1.x but it might take me a while.

**Comment by mightymaxv2** [comment]
Good deal! Thanks for your help.

**Comment by mattbeedle** [comment]
Ok, if you try installing version 1.5 that has the migration fix and faster imports back ported. I think it's all fine, I ran an import in an existing project successfully but I didn't check the database migrations. You'll need to install `activerecord-import` for the faster imports otherwise it will still import the old slow way. It's probably worth it though. Time goes from > 60 minutes to around 2 minutes on my laptop.

**Comment by mightymaxv2** [comment]
awesome! thanks!
